import Navbar from '../../components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { StoreProvider } from "./context/mainContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  const { children } = props
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>

      </body>
    </html >
  )
}
