"use client"
import ErrorModal from '../../components/ErrorModal'
import Navbar from '../../components/Navbar'
import { StoreProvider } from './context/Store'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  const { children } = props
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ErrorModal />
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html >
  )
}
